<?php

/**
 * Base class that represents a row from the 'filled_form' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Nov 22 04:32:46 2013
 *
 * @package    lib.model.om
 */
abstract class BaseFilledForm extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        FilledFormPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the form_id field.
	 * @var        int
	 */
	protected $form_id;

	/**
	 * The value for the inner_id field.
	 * @var        int
	 */
	protected $inner_id;

	/**
	 * The value for the operator_id field.
	 * @var        int
	 */
	protected $operator_id;

	/**
	 * The value for the operator_mail_sent field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $operator_mail_sent;

	/**
	 * The value for the user_mail_sent field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $user_mail_sent;

	/**
	 * The value for the name field.
	 * @var        string
	 */
	protected $name;

	/**
	 * The value for the email field.
	 * @var        string
	 */
	protected $email;

	/**
	 * The value for the phone field.
	 * @var        string
	 */
	protected $phone;

	/**
	 * The value for the referer field.
	 * @var        string
	 */
	protected $referer;

	/**
	 * The value for the data field.
	 * @var        string
	 */
	protected $data;

	/**
	 * The value for the is_closed field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $is_closed;

	/**
	 * The value for the notes field.
	 * @var        string
	 */
	protected $notes;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        ServiceForm
	 */
	protected $aServiceForm;

	/**
	 * @var        sfGuardUser
	 */
	protected $asfGuardUser;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'FilledFormPeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->operator_mail_sent = false;
		$this->user_mail_sent = false;
		$this->is_closed = false;
	}

	/**
	 * Initializes internal state of BaseFilledForm object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [form_id] column value.
	 * 
	 * @return     int
	 */
	public function getFormId()
	{
		return $this->form_id;
	}

	/**
	 * Get the [inner_id] column value.
	 * 
	 * @return     int
	 */
	public function getInnerId()
	{
		return $this->inner_id;
	}

	/**
	 * Get the [operator_id] column value.
	 * 
	 * @return     int
	 */
	public function getOperatorId()
	{
		return $this->operator_id;
	}

	/**
	 * Get the [operator_mail_sent] column value.
	 * 
	 * @return     boolean
	 */
	public function getOperatorMailSent()
	{
		return $this->operator_mail_sent;
	}

	/**
	 * Get the [user_mail_sent] column value.
	 * 
	 * @return     boolean
	 */
	public function getUserMailSent()
	{
		return $this->user_mail_sent;
	}

	/**
	 * Get the [name] column value.
	 * 
	 * @return     string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Get the [email] column value.
	 * 
	 * @return     string
	 */
	public function getEmail()
	{
		return $this->email;
	}

	/**
	 * Get the [phone] column value.
	 * 
	 * @return     string
	 */
	public function getPhone()
	{
		return $this->phone;
	}

	/**
	 * Get the [referer] column value.
	 * 
	 * @return     string
	 */
	public function getReferer()
	{
		return $this->referer;
	}

	/**
	 * Get the [data] column value.
	 * 
	 * @return     string
	 */
	public function getData()
	{
		return $this->data;
	}

	/**
	 * Get the [is_closed] column value.
	 * 
	 * @return     boolean
	 */
	public function getIsClosed()
	{
		return $this->is_closed;
	}

	/**
	 * Get the [notes] column value.
	 * 
	 * @return     string
	 */
	public function getNotes()
	{
		return $this->notes;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     FilledForm The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = FilledFormPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [form_id] column.
	 * 
	 * @param      int $v new value
	 * @return     FilledForm The current object (for fluent API support)
	 */
	public function setFormId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->form_id !== $v) {
			$this->form_id = $v;
			$this->modifiedColumns[] = FilledFormPeer::FORM_ID;
		}

		if ($this->aServiceForm !== null && $this->aServiceForm->getId() !== $v) {
			$this->aServiceForm = null;
		}

		return $this;
	} // setFormId()

	/**
	 * Set the value of [inner_id] column.
	 * 
	 * @param      int $v new value
	 * @return     FilledForm The current object (for fluent API support)
	 */
	public function setInnerId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->inner_id !== $v) {
			$this->inner_id = $v;
			$this->modifiedColumns[] = FilledFormPeer::INNER_ID;
		}

		return $this;
	} // setInnerId()

	/**
	 * Set the value of [operator_id] column.
	 * 
	 * @param      int $v new value
	 * @return     FilledForm The current object (for fluent API support)
	 */
	public function setOperatorId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->operator_id !== $v) {
			$this->operator_id = $v;
			$this->modifiedColumns[] = FilledFormPeer::OPERATOR_ID;
		}

		if ($this->asfGuardUser !== null && $this->asfGuardUser->getId() !== $v) {
			$this->asfGuardUser = null;
		}

		return $this;
	} // setOperatorId()

	/**
	 * Set the value of [operator_mail_sent] column.
	 * 
	 * @param      boolean $v new value
	 * @return     FilledForm The current object (for fluent API support)
	 */
	public function setOperatorMailSent($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->operator_mail_sent !== $v || $this->isNew()) {
			$this->operator_mail_sent = $v;
			$this->modifiedColumns[] = FilledFormPeer::OPERATOR_MAIL_SENT;
		}

		return $this;
	} // setOperatorMailSent()

	/**
	 * Set the value of [user_mail_sent] column.
	 * 
	 * @param      boolean $v new value
	 * @return     FilledForm The current object (for fluent API support)
	 */
	public function setUserMailSent($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->user_mail_sent !== $v || $this->isNew()) {
			$this->user_mail_sent = $v;
			$this->modifiedColumns[] = FilledFormPeer::USER_MAIL_SENT;
		}

		return $this;
	} // setUserMailSent()

	/**
	 * Set the value of [name] column.
	 * 
	 * @param      string $v new value
	 * @return     FilledForm The current object (for fluent API support)
	 */
	public function setName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name !== $v) {
			$this->name = $v;
			$this->modifiedColumns[] = FilledFormPeer::NAME;
		}

		return $this;
	} // setName()

	/**
	 * Set the value of [email] column.
	 * 
	 * @param      string $v new value
	 * @return     FilledForm The current object (for fluent API support)
	 */
	public function setEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->email !== $v) {
			$this->email = $v;
			$this->modifiedColumns[] = FilledFormPeer::EMAIL;
		}

		return $this;
	} // setEmail()

	/**
	 * Set the value of [phone] column.
	 * 
	 * @param      string $v new value
	 * @return     FilledForm The current object (for fluent API support)
	 */
	public function setPhone($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->phone !== $v) {
			$this->phone = $v;
			$this->modifiedColumns[] = FilledFormPeer::PHONE;
		}

		return $this;
	} // setPhone()

	/**
	 * Set the value of [referer] column.
	 * 
	 * @param      string $v new value
	 * @return     FilledForm The current object (for fluent API support)
	 */
	public function setReferer($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->referer !== $v) {
			$this->referer = $v;
			$this->modifiedColumns[] = FilledFormPeer::REFERER;
		}

		return $this;
	} // setReferer()

	/**
	 * Set the value of [data] column.
	 * 
	 * @param      string $v new value
	 * @return     FilledForm The current object (for fluent API support)
	 */
	public function setData($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->data !== $v) {
			$this->data = $v;
			$this->modifiedColumns[] = FilledFormPeer::DATA;
		}

		return $this;
	} // setData()

	/**
	 * Set the value of [is_closed] column.
	 * 
	 * @param      boolean $v new value
	 * @return     FilledForm The current object (for fluent API support)
	 */
	public function setIsClosed($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->is_closed !== $v || $this->isNew()) {
			$this->is_closed = $v;
			$this->modifiedColumns[] = FilledFormPeer::IS_CLOSED;
		}

		return $this;
	} // setIsClosed()

	/**
	 * Set the value of [notes] column.
	 * 
	 * @param      string $v new value
	 * @return     FilledForm The current object (for fluent API support)
	 */
	public function setNotes($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->notes !== $v) {
			$this->notes = $v;
			$this->modifiedColumns[] = FilledFormPeer::NOTES;
		}

		return $this;
	} // setNotes()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     FilledForm The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = FilledFormPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     FilledForm The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = FilledFormPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->operator_mail_sent !== false) {
				return false;
			}

			if ($this->user_mail_sent !== false) {
				return false;
			}

			if ($this->is_closed !== false) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->form_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->inner_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->operator_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->operator_mail_sent = ($row[$startcol + 4] !== null) ? (boolean) $row[$startcol + 4] : null;
			$this->user_mail_sent = ($row[$startcol + 5] !== null) ? (boolean) $row[$startcol + 5] : null;
			$this->name = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->email = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->phone = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->referer = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->data = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->is_closed = ($row[$startcol + 11] !== null) ? (boolean) $row[$startcol + 11] : null;
			$this->notes = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->created_at = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->updated_at = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 15; // 15 = FilledFormPeer::NUM_COLUMNS - FilledFormPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating FilledForm object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aServiceForm !== null && $this->form_id !== $this->aServiceForm->getId()) {
			$this->aServiceForm = null;
		}
		if ($this->asfGuardUser !== null && $this->operator_id !== $this->asfGuardUser->getId()) {
			$this->asfGuardUser = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FilledFormPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = FilledFormPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aServiceForm = null;
			$this->asfGuardUser = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FilledFormPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseFilledForm:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				FilledFormPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseFilledForm:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FilledFormPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseFilledForm:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(FilledFormPeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(FilledFormPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseFilledForm:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				FilledFormPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aServiceForm !== null) {
				if ($this->aServiceForm->isModified() || $this->aServiceForm->isNew()) {
					$affectedRows += $this->aServiceForm->save($con);
				}
				$this->setServiceForm($this->aServiceForm);
			}

			if ($this->asfGuardUser !== null) {
				if ($this->asfGuardUser->isModified() || $this->asfGuardUser->isNew()) {
					$affectedRows += $this->asfGuardUser->save($con);
				}
				$this->setsfGuardUser($this->asfGuardUser);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = FilledFormPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = FilledFormPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += FilledFormPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aServiceForm !== null) {
				if (!$this->aServiceForm->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aServiceForm->getValidationFailures());
				}
			}

			if ($this->asfGuardUser !== null) {
				if (!$this->asfGuardUser->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->asfGuardUser->getValidationFailures());
				}
			}


			if (($retval = FilledFormPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = FilledFormPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getFormId();
				break;
			case 2:
				return $this->getInnerId();
				break;
			case 3:
				return $this->getOperatorId();
				break;
			case 4:
				return $this->getOperatorMailSent();
				break;
			case 5:
				return $this->getUserMailSent();
				break;
			case 6:
				return $this->getName();
				break;
			case 7:
				return $this->getEmail();
				break;
			case 8:
				return $this->getPhone();
				break;
			case 9:
				return $this->getReferer();
				break;
			case 10:
				return $this->getData();
				break;
			case 11:
				return $this->getIsClosed();
				break;
			case 12:
				return $this->getNotes();
				break;
			case 13:
				return $this->getCreatedAt();
				break;
			case 14:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = FilledFormPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getFormId(),
			$keys[2] => $this->getInnerId(),
			$keys[3] => $this->getOperatorId(),
			$keys[4] => $this->getOperatorMailSent(),
			$keys[5] => $this->getUserMailSent(),
			$keys[6] => $this->getName(),
			$keys[7] => $this->getEmail(),
			$keys[8] => $this->getPhone(),
			$keys[9] => $this->getReferer(),
			$keys[10] => $this->getData(),
			$keys[11] => $this->getIsClosed(),
			$keys[12] => $this->getNotes(),
			$keys[13] => $this->getCreatedAt(),
			$keys[14] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = FilledFormPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setFormId($value);
				break;
			case 2:
				$this->setInnerId($value);
				break;
			case 3:
				$this->setOperatorId($value);
				break;
			case 4:
				$this->setOperatorMailSent($value);
				break;
			case 5:
				$this->setUserMailSent($value);
				break;
			case 6:
				$this->setName($value);
				break;
			case 7:
				$this->setEmail($value);
				break;
			case 8:
				$this->setPhone($value);
				break;
			case 9:
				$this->setReferer($value);
				break;
			case 10:
				$this->setData($value);
				break;
			case 11:
				$this->setIsClosed($value);
				break;
			case 12:
				$this->setNotes($value);
				break;
			case 13:
				$this->setCreatedAt($value);
				break;
			case 14:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = FilledFormPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setFormId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setInnerId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setOperatorId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setOperatorMailSent($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setUserMailSent($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setName($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setEmail($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setPhone($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setReferer($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setData($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setIsClosed($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setNotes($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setCreatedAt($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setUpdatedAt($arr[$keys[14]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(FilledFormPeer::DATABASE_NAME);

		if ($this->isColumnModified(FilledFormPeer::ID)) $criteria->add(FilledFormPeer::ID, $this->id);
		if ($this->isColumnModified(FilledFormPeer::FORM_ID)) $criteria->add(FilledFormPeer::FORM_ID, $this->form_id);
		if ($this->isColumnModified(FilledFormPeer::INNER_ID)) $criteria->add(FilledFormPeer::INNER_ID, $this->inner_id);
		if ($this->isColumnModified(FilledFormPeer::OPERATOR_ID)) $criteria->add(FilledFormPeer::OPERATOR_ID, $this->operator_id);
		if ($this->isColumnModified(FilledFormPeer::OPERATOR_MAIL_SENT)) $criteria->add(FilledFormPeer::OPERATOR_MAIL_SENT, $this->operator_mail_sent);
		if ($this->isColumnModified(FilledFormPeer::USER_MAIL_SENT)) $criteria->add(FilledFormPeer::USER_MAIL_SENT, $this->user_mail_sent);
		if ($this->isColumnModified(FilledFormPeer::NAME)) $criteria->add(FilledFormPeer::NAME, $this->name);
		if ($this->isColumnModified(FilledFormPeer::EMAIL)) $criteria->add(FilledFormPeer::EMAIL, $this->email);
		if ($this->isColumnModified(FilledFormPeer::PHONE)) $criteria->add(FilledFormPeer::PHONE, $this->phone);
		if ($this->isColumnModified(FilledFormPeer::REFERER)) $criteria->add(FilledFormPeer::REFERER, $this->referer);
		if ($this->isColumnModified(FilledFormPeer::DATA)) $criteria->add(FilledFormPeer::DATA, $this->data);
		if ($this->isColumnModified(FilledFormPeer::IS_CLOSED)) $criteria->add(FilledFormPeer::IS_CLOSED, $this->is_closed);
		if ($this->isColumnModified(FilledFormPeer::NOTES)) $criteria->add(FilledFormPeer::NOTES, $this->notes);
		if ($this->isColumnModified(FilledFormPeer::CREATED_AT)) $criteria->add(FilledFormPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(FilledFormPeer::UPDATED_AT)) $criteria->add(FilledFormPeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(FilledFormPeer::DATABASE_NAME);

		$criteria->add(FilledFormPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of FilledForm (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setFormId($this->form_id);

		$copyObj->setInnerId($this->inner_id);

		$copyObj->setOperatorId($this->operator_id);

		$copyObj->setOperatorMailSent($this->operator_mail_sent);

		$copyObj->setUserMailSent($this->user_mail_sent);

		$copyObj->setName($this->name);

		$copyObj->setEmail($this->email);

		$copyObj->setPhone($this->phone);

		$copyObj->setReferer($this->referer);

		$copyObj->setData($this->data);

		$copyObj->setIsClosed($this->is_closed);

		$copyObj->setNotes($this->notes);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     FilledForm Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     FilledFormPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new FilledFormPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a ServiceForm object.
	 *
	 * @param      ServiceForm $v
	 * @return     FilledForm The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setServiceForm(ServiceForm $v = null)
	{
		if ($v === null) {
			$this->setFormId(NULL);
		} else {
			$this->setFormId($v->getId());
		}

		$this->aServiceForm = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the ServiceForm object, it will not be re-added.
		if ($v !== null) {
			$v->addFilledForm($this);
		}

		return $this;
	}


	/**
	 * Get the associated ServiceForm object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     ServiceForm The associated ServiceForm object.
	 * @throws     PropelException
	 */
	public function getServiceForm(PropelPDO $con = null)
	{
		if ($this->aServiceForm === null && ($this->form_id !== null)) {
			$this->aServiceForm = ServiceFormPeer::retrieveByPk($this->form_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aServiceForm->addFilledForms($this);
			 */
		}
		return $this->aServiceForm;
	}

	/**
	 * Declares an association between this object and a sfGuardUser object.
	 *
	 * @param      sfGuardUser $v
	 * @return     FilledForm The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setsfGuardUser(sfGuardUser $v = null)
	{
		if ($v === null) {
			$this->setOperatorId(NULL);
		} else {
			$this->setOperatorId($v->getId());
		}

		$this->asfGuardUser = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfGuardUser object, it will not be re-added.
		if ($v !== null) {
			$v->addFilledForm($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfGuardUser object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfGuardUser The associated sfGuardUser object.
	 * @throws     PropelException
	 */
	public function getsfGuardUser(PropelPDO $con = null)
	{
		if ($this->asfGuardUser === null && ($this->operator_id !== null)) {
			$this->asfGuardUser = sfGuardUserPeer::retrieveByPk($this->operator_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->asfGuardUser->addFilledForms($this);
			 */
		}
		return $this->asfGuardUser;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aServiceForm = null;
			$this->asfGuardUser = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseFilledForm:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseFilledForm::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseFilledForm
