<?php


/**
 * Skeleton subclass for representing a row from the 'advertise' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 10/04/13 17:07:13
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Advertise extends BaseAdvertise {
    
    public function getHtmlImagePath() {
        $path = str_replace(sfConfig::get('sf_web_dir'), '', sfConfig::get('sf_upload_dir')).'/'.sfConfig::get('app_adv_dir').'/'.$this->getSliderImage();
        $path = str_replace(DIRECTORY_SEPARATOR, '/', $path);
        return $path;
    }
    
    function delete(PropelPDO $con = null) {
        $path = sfConfig::get('sf_upload_dir').DIRECTORY_SEPARATOR.sfConfig::get('app_adv_dir').DIRECTORY_SEPARATOR.$this->getSliderImage();
        if (is_file($path)) {
            try {
                unlink($path);
            } catch (Exception $exc) {}
        }
        parent::delete($con);
    }
    
    function setSliderImage($v) {
        if (!$v && 0 == strlen($v)) {
            return;
        }
        return parent::setSliderImage($v);
    }
} // Advertise
