<?php


/**
 * Skeleton subclass for performing query and update operations on the 'car_label' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Oct 30 22:07:59 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CarLabelPeer extends BaseCarLabelPeer {

    public static function retrieveBySlug($slug) {
        $c = new Criteria();
        $c->add(self::SLUG, $slug);
        return self::doSelectOne($c);
    }

    public static function retrieveIdBySlug($slug) {
        $con = Propel::getConnection();
        $q = "SELECT ".self::ID." FROM ".self::TABLE_NAME." WHERE ".self::SLUG." = :slug";
        $stmt = $con->prepare($q);
        $stmt->execute(array(
            ':slug' => $slug
        ));
        $id = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM))
            $id = $row[0];
        return $id;
    }

    public static function tryAdd($name, $slug, $parentId = null) {
        $cl = self::retrieveBySlug($slug);
        if (!$cl) {
            $cl = new CarLabel();
            $cl->setName($name)
                ->setSlug($slug)
                ->setParentId($parentId)
                ->save();
        }
        return $cl;
    }
} // CarLabelPeer
