<?php


/**
 * Skeleton subclass for performing query and update operations on the 'car_product' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Nov 21 06:28:33 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CarProductPeer extends BaseCarProductPeer {
    public static function tryAdd($carId, $productId) {
        $cp = self::retrieveByPK($carId, $productId);
        if (!$cp) {
            $cp = new CarProduct();
            $cp->setCarId($carId)
                ->setProductId($productId)
                ->save();
        }
        return $cp;
    }
} // CarProductPeer
