<?php


/**
 * Skeleton subclass for representing a row from the 'car_product' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Nov 21 06:28:33 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CarProduct extends BaseCarProduct {
} // CarProduct
