<?php


/**
 * Skeleton subclass for representing a row from the 'category' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 11/03/13 13:19:03
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Category extends BaseCategory {
    public function __toString() {
        return $this->getName();
    }

    public function checkCarId($carId) {
        $c = new Criteria();
        if (!is_null($this->getParentId())) {
            $c->add(CarCategoryPeer::CAR_ID, $carId);
            $c->add(CarCategoryPeer::CATEGORY_ID, $this->getId());
        } else {
            $c->addAlias('c', CategoryPeer::TABLE_NAME);
            $c->addJoin(CategoryPeer::alias('c', CategoryPeer::ID), CategoryPeer::PARENT_ID);
            $c->addJoin(CategoryPeer::ID, CarCategoryPeer::CATEGORY_ID);
            $c->addAlias('c.ID', $this->getId());
            $c->add(CarCategoryPeer::CAR_ID, $carId);
        }
        return CarCategoryPeer::doCount($c) > 0;
    }
} // Category
