<?php

/**
 * Skeleton subclass for performing query and update operations on the 'category' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 11/03/13 13:19:03
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CategoryPeer extends BaseCategoryPeer {

    public static function retrieveByName($name) {
        $c = new Criteria();
        $c->add(self::NAME, $name);
        return self::doSelectOne($c);
    }

    public static function retrieveBySlug($slug, $parentId = null) {
        $c = new Criteria();
        $c->add(self::SLUG, $slug);
        if ($parentId)
            $c->add(self::PARENT_ID, $parentId);
        return self::doSelectOne($c);
    }

    public static function tryAdd($catName, $catSlug, $parentId = null) {
        $cat = self::retrieveBySlug($catSlug, $parentId);
        if (!$cat) {
            $cat = new Category();
            $cat->setParentId($parentId);
            $cat->setName($catName);
            $cat->setSlug($catSlug);
            $cat->save();
        }
        return $cat;
    }

    public static function getSelectTree($addEmpty) {
        $con = Propel::getConnection();
        $stmt = $con->prepare('SELECT '.self::ID.', IF('.self::PARENT_ID.' IS NULL, '.self::NAME.', CONCAT(\'- \', '.self::NAME.')), IF('.self::PARENT_ID.' IS NULL, '.self::ID.', CONCAT('.self::PARENT_ID.', \'-\', '.self::SLUG.')) AS `ordering` FROM '.self::TABLE_NAME.' ORDER BY `ordering`;');
        $stmt->execute();
        $list = array();
        if ($addEmpty) {
            $list[''] = '';
        }
        while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $list[ $row[0] ] = $row[1];
        }
        return $list;
    }

}

// CategoryPeer
