<?php


/**
 * Skeleton subclass for representing a row from the 'pages' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 09/14/13 13:02:22
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Pages extends BasePages {
    
    /**
     * return $this->getIs301redirect();
     * @return boolean
     */
    function is301() {
        return $this->getIs301redirect();
    }
    
    /**
     * 
     * @return string
     */
    function getTrimmedSlug() {
        $slug = preg_replace("/^\/*/", '', $this->getSlug());
        $slug = preg_replace("/\/*$/", '', $slug).'/';
        return $slug;
    }
    
    /**
     * 
     * @return string
     */
    function getTrimmedOldLinkSlug() {
        $slug = preg_replace("/^\/*/", '', $this->getTrimmedOldLinkSlug());
        $slug = preg_replace("/\/*$/", '', $slug).'/';
        return $slug;
    }
} // Pages
