<?php


/**
 * Skeleton subclass for performing query and update operations on the 'product' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Nov 17 15:44:40 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ProductPeer extends BaseProductPeer {

    public static function retrieveBySlug($slug) {
        $c = new Criteria();
        $c->add(self::SLUG, $slug);
        return self::doSelectOne($c);
    }

    public static function tryAdd($catId, $amount, $uid, $analog_uid, $slug, $name, $distrib_price) {
        $p = self::retrieveBySlug($slug);
        if (!$p) {
            $p = new Product();
            $p->setCategoryId($catId);
            $p->setAmount($amount);
            $p->setUid($uid);
            $p->setAnalogUid($analog_uid);
            $p->setName($name);
            $p->setSlug($slug);
            $p->setDistribPrice($distrib_price);
            $p->save();
        }
        return $p;
    }

} // ProductPeer
