<?php


/**
 * Skeleton subclass for representing a row from the 'product' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Nov 17 15:44:40 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Product extends BaseProduct {
    public function __toString() {
        return $this->getName();
    }

    public function getUsability($delimiter = ', ') {
        return ProductPeer::getUsability($this->getId(), $delimiter);
    }
} // Product
