<?php

/**
 * Skeleton subclass for performing query and update operations on the 'service_form' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 09/24/13 12:36:54
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ServiceFormPeer extends BaseServiceFormPeer {

    public static function retrieveByName($name) {
        $c = new Criteria();
        $c->add(self::NAME, $name);
        return self::doSelectOne($c);
    }
    
    public static function getAutoincrement($formId) {
        $con = Propel::getConnection();
        $sql = 'SELECT '.self::AUTO_INC.' FROM '.self::TABLE_NAME.' WHERE '.self::ID.' = :id ';
        $stmt = $con->prepare($sql);
        $stmt->execute(array(':id' => $formId));
        $autoinc = 1;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $autoinc = (int)$row[0];
        }
        return $autoinc;
    }
    public static function updateAutoincrement($formId, $autoinc) {
        $con = Propel::getConnection();
        $sql = 'UPDATE '.self::TABLE_NAME.' SET '.self::AUTO_INC.' = :auto_inc WHERE '.self::ID.' = :id ';
        $stmt = $con->prepare($sql);
        $stmt->execute(array(':id' => $formId, ':auto_inc' => $autoinc));
        return $stmt->rowCount();
    }

}

// ServiceFormPeer
