<?php


/**
 * Skeleton subclass for representing a row from the 'service_form' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 09/24/13 12:36:54
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ServiceForm extends BaseServiceForm {

	/**
	 * Initializes internal state of ServiceForm object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}
        
        public function __toString() {
            return $this->getName();
        }
        
        public function save(PropelPDO $con = null) {
            $isNew = $this->isNew();
            $affectedRow = parent::save($con);
            
            if ($affectedRow && $isNew) {
                foreach (sfConfig::get('app_pre_fields') as $fieldInfo) {
                    $field = new Field();
                    $field->setFormId($this->getId());
                    $field->setIsRequired($fieldInfo['is_required']);
                    $field->setIsDeletable($fieldInfo['is_deletable']);
                    $field->setSort($fieldInfo['sort']);
                    $field->setType($fieldInfo['type']);
                    $field->setFieldName($fieldInfo['field_name']);
                    $field->setTitle($fieldInfo['title']);
                    $field->setTip($fieldInfo['tip']);
                    $field->save();
                }
            }
        }
        
        public function getOrderedFields() {
            $c = new Criteria();
            $c->addAscendingOrderByColumn(FieldPeer::SORT);
            return $this->getFields($c);
        }

} // ServiceForm
